update some files

diff --git a/config/modules/maven b/config/modules/maven
--- a/config/modules/maven
+++ b/config/modules/maven
@@ -17,20 +17,20 @@ MavenActionAdapter(){
 
 MavenArchiveController(){
      maven_archive_target=$PKG_FILE
-    archive_saved_to_name=$JKS_DL_DIR/$MAVEN_ARCHIVE_DIR/$BUILD_NUMBER-$(basename $maven_archive_target)
+    archive_saved_to_name=$JKS_DL_DIR/$MAVEN_ARCHIVE_DIR/$BUILD_NUMBER-$(basename $maven_archive_target)         
           old_archive_dir=$JKS_DL_DIR/$MAVEN_ARCHIVE_DIR/`date -d "$MAVEN_ARCHIVE_EXPIRES days ago" ++%Y/%m/%d`
                      astd=$(dirname $archive_saved_to_name)
     if [ ! -d $astd ]
-    then
+    then 
         mkdir -p $astd
         msg i "Created dir $astd"
     fi
 
     test -f "$maven_archive_target" && cp -rf $maven_archive_target $archive_saved_to_name
-
+            
     msg i "Maven Project Archived to:  $archive_saved_to_name"
     msg i "Maven Project Archived URL: $JKS_DL_URL/$MAVEN_ARCHIVE_DIR/$(basename $archive_saved_to_name)"
-    msg i "Maven Project Archived MD5: `md5sum $archive_saved_to_name | awk '{print $1}'`"
+    #msg i "Maven Project Archived MD5: `md5sum $archive_saved_to_name | awk '{print $1}'`"
 
     if [ -d "$old_archive_dir" ]
     then
@@ -51,8 +51,8 @@ MavenBuild(){
     msg i "Using $MAVEN_VERSION"
     msg i "With maven options: $MAVEN_OPTS"
     $MAVEN_CMD $MAVEN_OPTS
+    
+    test $? != 0 && msg error "Failed to build, aborted"     
 
-    test $? != 0 && msg error "Failed to build, aborted"
-
-    check exist $APP_FILE
+    #check exist $APP_FILE
 }
